packages:
  - 'frontend'
  - 'backend'
  - 'strapi'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  '@swc/core': true
  sharp: true
  core-js-pure: true
  argon2: true
